version: '3.3'
services:
    config-postgres:
        restart: always
        ports:
          - 5432:5432
	environment:
          - "BRIDGECOM_DB_USER=bridgecom"
          - "BRIDGECOM_DB_PASSWORD=dkghrkety_345df"
          - "BRIDGECOM_DB_NAME=bridgecomdb"
          - "BRIDGECOM_DB_SCHEME=bridgecom"
          - "POSTGRES_PASSWORD="
        build: './postgres'
        networks:
          - bridgecom-network
    config-core:
        container_name: core
        build:
            context: core
            dockerfile: Dockerfile
        image: core:latest
        ports:
            - 88:8080
        depends_on:
            - "config-postgres"
        networks:
            - bridgecom-network
        volumes:
            - $HOME/.m2/repository:/root/.m2/repository
            - ./core/target:/core/target
        logging:
            driver: json-file
volumes:
    bridgecom-config-repo:
        external: false
networks:
    bridgecom-network:
        driver: bridge