version: '3.3'
services:
    config-postgres:
        restart: always
        ports:
          - 5432:5432
    environment:
          - "MEME_DB_USER=meme"
          - "MEME_DB_PASSWORD=dkghrkety_345df"
          - "MEME_DB_NAME=memedb"
          - "MEME_DB_SCHEME=meme"
          - "POSTGRES_PASSWORD="
        build: './postgres'
        networks:
          - meme-network
    config-core:
        container_name: core
        build:
            context: core
            dockerfile: Dockerfile
        image: core:latest
        ports:
            - 88:8080
        depends_on:
            - "config-postgres"
        networks:
            - meme-network
        volumes:
            - $HOME/.m2/repository:/root/.m2/repository
            - ./core/target:/core/target
        logging:
            driver: json-file
volumes:
    meme-config-repo:
        external: false
networks:
    meme-network:
        driver: bridge